# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: MCSRRanked SDK
site_description: TypeScript SDK for the MCSR Ranked API
site_url: https://notava1ble.github.io/mcsrranked-sdk/
repo_url: https://github.com/Notava1ble/mcsrranked-sdk
repo_name: Notava1ble/mcsrranked-sdk
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

strict: true
